theme = "vixelated"
[editor]
auto-completion = true
auto-format = true
auto-save = true
color-modes = true
line-number = "relative"
text-width = 80
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "▏"
render = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "file-base-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
separator = "│"

[editor.statusline.mode]
insert = "I"
normal = "N"
select = "S"
